# Практическое задание 7

## по теме: "Многомерный статистический анализ. Линейная регрессия"

**Задача 1.**

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): 

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], 

ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. 

Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). 

Произвести расчет как с использованием intercept, так и без.

**Решение с использованием intercept:**

In [1]:
import numpy as np

$$y = a + bx$$

In [2]:
x = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110], dtype=np.float64)

In [3]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832], dtype=np.float64)

$$b = \frac{\overline{yx} - \overline{y} \cdot {\overline{x}}}{\overline{x^2} - (\overline{x})^2}$$

In [4]:
b = (np.mean(x * y) - np.mean(x) * np.mean(y)) / (np.mean(x**2) - np.mean(x) ** 2)
b

2.620538882402765

$$a = \overline{y} - b \cdot {\overline{x}}$$

In [5]:
a = np.mean(y) - b * np.mean(x)
a

444.1773573243596

$$y = 444.2 + 2.6 \cdot x$$

**Решение без использования intercept:**

In [6]:
X = x.reshape((10, 1))
X

array([[ 35.],
       [ 45.],
       [190.],
       [200.],
       [ 40.],
       [ 70.],
       [ 54.],
       [150.],
       [120.],
       [110.]])

In [7]:
Y = y.reshape((10, 1))
Y

array([[401.],
       [574.],
       [874.],
       [919.],
       [459.],
       [739.],
       [653.],
       [902.],
       [746.],
       [832.]])

In [8]:
B = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T @ Y)
B

array([[5.88982042]])

$$y = 5.9 \cdot x$$

**Задача 2.**

Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [9]:
def mse(B1, y=y, x=x, n=10):
    return np.sum((B1 * x - y) ** 2) / n

In [10]:
B1 = 0.1
n = 10

In [11]:
alfa = 1e-6
alfa

1e-06

In [12]:
for i in range(10000):
    B1 = B1 - alfa * (2 / n) * np.sum((B1 * x -y) * x)
    if i % 500 == 0:
        print(f'Interaction : {i}, B1 = {B1}, mse = {mse(B1)}')

Interaction : 0, B1 = 0.25952808, mse = 493237.7212546963
Interaction : 500, B1 = 5.889815595583751, mse = 56516.858416040064
Interaction : 1000, B1 = 5.8898204201285544, mse = 56516.85841571941
Interaction : 1500, B1 = 5.889820420132673, mse = 56516.85841571943
Interaction : 2000, B1 = 5.889820420132673, mse = 56516.85841571943
Interaction : 2500, B1 = 5.889820420132673, mse = 56516.85841571943
Interaction : 3000, B1 = 5.889820420132673, mse = 56516.85841571943
Interaction : 3500, B1 = 5.889820420132673, mse = 56516.85841571943
Interaction : 4000, B1 = 5.889820420132673, mse = 56516.85841571943
Interaction : 4500, B1 = 5.889820420132673, mse = 56516.85841571943
Interaction : 5000, B1 = 5.889820420132673, mse = 56516.85841571943
Interaction : 5500, B1 = 5.889820420132673, mse = 56516.85841571943
Interaction : 6000, B1 = 5.889820420132673, mse = 56516.85841571943
Interaction : 6500, B1 = 5.889820420132673, mse = 56516.85841571943
Interaction : 7000, B1 = 5.889820420132673, mse = 56516.8